apiVersion : apps/v1
kind: Deployment
metadata:
  name: go-webapp
  namespace: _{_NAMESPACE_}_
spec:
  replicas: _{_REPLICAS_}_
  selector:
    matchLabels:
      app: go-webapp
  template:
    metadata:
      labels:
        app: go-webapp 
    spec:
      containers:
        - name: go-webapp
          image: _{_IMAGE_}_
          imagePulPolicy: Always
          ports:
          - containerPort: 3000
            name: http
            protocol: TCP