apiVersion: v1
kind: Service
metadata:
    name: app1nginxaks
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
        app: app1nginxaks


az ad sp create-for-rbac --name aks_terraform_sp --role Contributor --scopes /subscriptions/7fb5df25-588e-486b-adc9-c36f5f78a293/resourceGroups/oba_rg
